# This is a basic workflow to help you get started with Actions

name: Flatten SLDR and publish to staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Install our private key for uploading deliverable
    - uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: |
          ${{secrets.UPLOADER_SSH_KEY}}
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Check-out the tooling
    - uses: actions/checkout@v2
      with:
        repository: silnrsi/sldrtools
        path: tools
    
    # Install SLDR tools
    - name: Setup sldrtools
      working-directory: tools
      run: pip install .
      
    # Runs a single command using the runners shell
    #- name: sldr-flat-publish
    #  run: /sldr-flat-publish.sh -t -S scriptsource.org
