# This is a basic workflow to help you get started with Actions

name: Flatten SLDR and publish to staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - sldr/**
    branches: [ master ]
  pull_request:
    - sldr/**
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      STAGE: sldr-staging
      TARGET: ${{secrets.UPLOAD_TARGET}}
      RSYNC_OPTS: -aP --no-p --no-g --no-t --compress --del -e "ssh -o StrictHostKeyChecking=no"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Install our private key for uploading deliverable
    - uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: |
          ${{secrets.UPLOADER_SSH_KEY}}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Check-out the tooling
    - uses: actions/checkout@v2
      with:
        repository: silnrsi/sldrtools
        path: tools
    
    # Install SLDR tools
    - name: Setup sldrtools
      working-directory: tools
      run: pip install .
      
    # Flatten SLDR
    - name: Generate unflattened sldr
      run: python3 tools/scripts/ldmlflatten -o unflat -i sldr -a -c -g
    
    - name: Generate flattened sldr
      run: python3 tools/scripts/ldmlflatten -o flat -i sldr -a -A -g
      
    # Upload results
    - name: Upload SLDR to /ldml/${{env.STAGE}}
      run: rsync ${{env.RSYNC_OPTS}} extras sldr ${{env.TARGET}}/local/ldml/${{env.STAGE}}/
    
    - name: Upload flattened SLDR to /ldml-api/data/${{env.STAGE}}
      run: rsync ${{env.RSYNC_OPTS}} --chmod=Dug=rwx flat unflat ${{env.TARGET}}/sites/s/ldml-api/data/${{env.STAGE}}/
  
